name: IWD CI

description: Runs IWD's CI

#
# Due to the special requirements of test-runner, docker must be built and ran
# manually. This is for a few reasons:
#
# - UML requires --privileged since its touching /dev/*
# - /dev/shm needs to be mounted without NOEXEC, which docker does not do. This
#   is remedied by mounting the host /dev/shm directly
# - UML needs /home/<user>/.uml, and the users home directory is not mounted
#   by default.
#

inputs:
  tests:
    description: Tests to run (comma separated, no spaces)
    default: all
  kernel:
    description: Kernel version
    default: '5.16'
  hostapd_version:
    description: Hostapd and wpa_supplicant version
    default: '2_10'
  github_token:
    required: true
  email_token:
    required: true
  patchwork_token:
    required: true
  repository:
    required: true
  ref_branch:
    required: true
  ci:
    description: The CI to run (main, musl)
    default: 'main'

runs:
  using: 'composite'
  steps:
    - name: Docker
      uses: IWDTestBot/ci-docker@master
      env:
        INPUT_KERNEL: ${{ inputs.kernel }}
        INPUT_HOSTAPD_VERSION: ${{ inputs.hostapd_version }}
        INPUT_TESTS: ${{ inputs.tests }}
        GITHUB_TOKEN: ${{ inputs.github_token }}
        EMAIL_TOKEN: ${{ inputs.email_token }}
        PATCHWORK_TOKEN : ${{ inputs.patchwork_token }}
        GITHUB_REPO: ${{ inputs.repository }}
        REF_BRANCH: ${{ inputs.ref_branch }}
      with:
        image: Dockerfile.${{ inputs.ci }}
        action_path: ${{ github.action_path }}
        options: --privileged -v /dev/shm:/dev/shm
